'use strict';
// 解説は下記資料を参考にしたゲーム独自の要約・問いです。公式研修や認証ではありません。
const lessons = [
  {image:'arrival',alt:'朝のキャンプに到着する家族と、無線で連絡を取る現地スタッフ',title:'人数の先に、一人ひとりの必要がある',body:'同じ100人でも、必要な支援は同じではありません。まず何が急を要するか、誰が支援にアクセスしにくいかを確認する視点が大切です。住民も状況を知る協力者です。',question:'最初の報告を聞いて、追加で確かめたいのは？',answers:['年齢別の人数だけで、全員の優先順位を決める','負傷の状態や移動の難しさ、本人が困っていること'],correct:1,explanation:'人数は出発点です。状態や生活上の障壁を聞き取ると、同じ年齢でも異なる必要が見えてきます。ゲームでは負傷者を同じ数値で扱いますが、現実の緊急性はそれだけでは判断できません。',reflect:'あなたの最初の判断には、どんな追加情報があれば自信を持てますか？',source:'chs'},
  {image:'supplies',alt:'テントと水の容器をトラックから協力して降ろす住民とスタッフ',title:'「届いた」と「使える」は違う',body:'水、食事、住居、保健はつながっています。物資の合計だけでなく、誰に届き、使える状態になっているかを考えてみましょう。',question:'水100人分が到着しました。次に確かめたいのは？',answers:['列に並べない人も受け取れるか、運搬や保管で困っていないか','合計100人分あるので、配布の確認は終える'],correct:0,explanation:'このゲームの「100人分」は簡略化した数字です。実際には水の質や量、運びやすさなども検討が必要です。到着した数だけでは、全員が使えるとは限りません。',reflect:'物資が足りていても、受け取れない人がいるとしたら？',source:'sphere'},
  {image:'health',alt:'診療用テントで包帯を巻いた成人と目線を合わせて話す医療スタッフ',title:'健康を支える分野は、ひとつではない',body:'保健と水・衛生は別々の支援分野ですが、人の暮らしの中では結びついています。ひとつの課題に対応した後も、他の不足を見直します。',question:'負傷者への対応が終わったら、何を考える？',answers:['けがへの対応が済めば、健康に関する課題はすべて解決','水や衛生設備など、生活環境の不足も確認する'],correct:1,explanation:'「治療済み」はゲーム内の一項目です。生活を支える他の分野も確認することで、支援の抜けを考えられます。この問いは診断や治療方法を示すものではありません。',reflect:'医療を選ぶことで、後回しになった課題はありましたか？',source:'sphere'},
  {image:'food',alt:'日陰の共同調理場で住民とスタッフが食事を準備する様子',title:'住民は、支援を一緒につくる人',body:'支援を受ける人にも、経験や知識、希望があります。何が必要か、どんな方法がよいかを一緒に考えることで、支援のあり方が変わります。',question:'炊き出しへの住民参加で、大切なのは？',answers:['希望や経験を聞き、参加しない人も支援を受けられるようにする','食事を受け取る条件として、全員に調理を義務づける'],correct:0,explanation:'参加は、支援を受けるための交換条件にするものではありません。住民の主体性を尊重し、無理なく関われる方法を考えます。ゲームの「信頼」は現実の関係性を正確に測る数字ではありません。',reflect:'住民に相談すると、あなたの計画の何が変わりそうですか？',source:'chs'},
  {image:'shelter',alt:'夕暮れにテントを整え、相談窓口でスタッフと話す住民',title:'声を届けられることも、支援の一部',body:'困りごとがあっても、言葉や立場の違いから伝えられないことがあります。物資を届けるだけでなく、住民が支援のあり方について声を届けられる関係も考えます。',question:'相談窓口が「ある」だけで十分でしょうか？',answers:['窓口を設置したら、使いやすさは確認しなくてよい','住民が場所や使い方を知り、安心して話せるかも確かめる'],correct:1,explanation:'窓口の設置は出発点です。相談したい人が利用できるか、声が次の対応に反映されるかを考えてみましょう。',reflect:'声を上げにくい人の意見を聞くには、何を工夫できますか？',source:'chs'},
  {image:'planning',alt:'夜のテントで住民代表とスタッフが地図を囲み翌日の計画を話し合う様子',title:'振り返りは、次の支援を変えるために',body:'支援は一日で終わりません。何を実施したかに加え、何が届かなかったか、住民がどう感じているかを確認し、次の計画を見直します。',question:'翌日のチームへ引き継ぐと役立つのは？',answers:['使った金額だけ','対応済みのこと、残る不足、住民からの声、次に確認すること'],correct:1,explanation:'活動の記録は改善の材料になります。残金が多いことだけを成功とはせず、未対応の必要と選択の理由を共有しましょう。',reflect:'もう一度遊ぶなら、どの判断を、なぜ変えたいですか？',source:'chs'}
];
const learningSources={sphere:{label:'Sphere Handbook：支援の4分野',url:'https://spherestandards.org/handbook/'},chs:{label:'CHS 2024：権利・尊厳と住民の主体性',url:'https://www.corehumanitarianstandard.org/the-standard'}};
function sceneMarkup(index){const lesson=lessons[index];return `<figure class="scene"><img src="assets/${lesson.image}.jpg" alt="${lesson.alt}" width="1536" height="1024" decoding="async"><figcaption><span>${scenarios[index].time} / ${scenarios[index].label}</span></figcaption></figure>`;}
function lessonMarkup(index){const l=lessons[index],source=learningSources[l.source];return `<section class="learning" aria-labelledby="lesson-title"><p class="eyebrow">FIELD NOTE / この判断から学ぶ</p><h3 id="lesson-title">${l.title}</h3><p>${l.body}</p><div class="knowledge"><h4>ひとつ考えてみよう</h4><p>${l.question}</p><div class="quiz-options">${l.answers.map((a,i)=>`<button type="button" data-answer="${i}" aria-pressed="false">${a}</button>`).join('')}</div><p id="quiz-feedback" class="quiz-feedback" aria-live="polite"></p></div><p class="source">参考：<a href="${source.url}" target="_blank" rel="noopener noreferrer">${source.label} ↗</a>（解説・問いは本ゲーム独自）</p></section>`;}
function bindLesson(index){const buttons=document.querySelectorAll('[data-answer]');function show(answer){const l=lessons[index];buttons.forEach(button=>{button.disabled=true;button.setAttribute('aria-pressed',String(Number(button.dataset.answer)===answer));});document.getElementById('quiz-feedback').textContent=(answer===l.correct?'その視点が大切です。':'別の視点も考えてみましょう。')+l.explanation;}buttons.forEach(button=>button.onclick=()=>{const answer=Number(button.dataset.answer);state.quizAnswers[index]=answer;show(answer);});if(state.quizAnswers[index]!==undefined)show(state.quizAnswers[index]);}
function learningRecap(){return `<section class="learning-recap"><p class="eyebrow">TAKEAWAYS / 持ち帰る学び</p><h3>あなたの6つの判断を振り返る</h3><p>開くと、自分の選択と考えるヒントを読み返せます。</p>${lessons.map((l,i)=>`<details><summary>${scenarios[i].time}　${l.title}</summary><p><strong>あなたの選択：</strong>${state.history[i].title}（${state.history[i].cost}万円）</p><p>${l.body}</p><p class="reflection">${l.reflect}</p></details>`).join('')}<label for="reflection-note">次に変えたい判断と、その理由を一言で</label><textarea id="reflection-note" rows="3" maxlength="1000" placeholder="例：物資の数だけでなく、受け取れない人がいないか確認したい。"></textarea><small>メモはこの画面だけに保持され、送信・保存されません。</small></section>`;}
if(typeof module!=='undefined')module.exports={lessons,learningSources};
